apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: default
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
